/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Affectation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Affectation#getAttribut <em>Attribut</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Affectation#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getAffectation()
 * @model
 * @generated
 */
public interface Affectation extends Declaration
{
  /**
   * Returns the value of the '<em><b>Attribut</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribut</em>' containment reference.
   * @see #setAttribut(Attribut)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getAffectation_Attribut()
   * @model containment="true"
   * @generated
   */
  Attribut getAttribut();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Affectation#getAttribut <em>Attribut</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribut</em>' containment reference.
   * @see #getAttribut()
   * @generated
   */
  void setAttribut(Attribut value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(ExpressionNumerique)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getAffectation_Expression()
   * @model containment="true"
   * @generated
   */
  ExpressionNumerique getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Affectation#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(ExpressionNumerique value);

} // Affectation
