/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Booleen</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Booleen#getVal <em>Val</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Booleen#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Booleen#getExp1 <em>Exp1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Booleen#getComp <em>Comp</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Booleen#getExp2 <em>Exp2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getBooleen()
 * @model
 * @generated
 */
public interface Booleen extends BooleanContraire
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(String)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getBooleen_Val()
   * @model
   * @generated
   */
  String getVal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Booleen#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(VariableBooleene)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getBooleen_Var()
   * @model containment="true"
   * @generated
   */
  VariableBooleene getVar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Booleen#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VariableBooleene value);

  /**
   * Returns the value of the '<em><b>Exp1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp1</em>' containment reference.
   * @see #setExp1(ExpressionNumerique)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getBooleen_Exp1()
   * @model containment="true"
   * @generated
   */
  ExpressionNumerique getExp1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Booleen#getExp1 <em>Exp1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp1</em>' containment reference.
   * @see #getExp1()
   * @generated
   */
  void setExp1(ExpressionNumerique value);

  /**
   * Returns the value of the '<em><b>Comp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp</em>' attribute.
   * @see #setComp(String)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getBooleen_Comp()
   * @model
   * @generated
   */
  String getComp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Booleen#getComp <em>Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp</em>' attribute.
   * @see #getComp()
   * @generated
   */
  void setComp(String value);

  /**
   * Returns the value of the '<em><b>Exp2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp2</em>' containment reference.
   * @see #setExp2(ExpressionNumerique)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getBooleen_Exp2()
   * @model containment="true"
   * @generated
   */
  ExpressionNumerique getExp2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Booleen#getExp2 <em>Exp2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp2</em>' containment reference.
   * @see #getExp2()
   * @generated
   */
  void setExp2(ExpressionNumerique value);

} // Booleen
