/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends EObject
{
} // Declaration
