/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Numerique</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.ExpressionNumerique#getExp <em>Exp</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.ExpressionNumerique#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getExpressionNumerique()
 * @model
 * @generated
 */
public interface ExpressionNumerique extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.rulesUNO.Entier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference list.
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getExpressionNumerique_Exp()
   * @model containment="true"
   * @generated
   */
  EList<Entier> getExp();

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getExpressionNumerique_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

} // ExpressionNumerique
