/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instructions Bloc</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getInstructionsBloc()
 * @model
 * @generated
 */
public interface InstructionsBloc extends Instruction
{
} // InstructionsBloc
