/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getInstruction()
 * @model
 * @generated
 */
public interface Instruction extends Declaration
{
} // Instruction
