/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Uno#getNbJoueur <em>Nb Joueur</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Uno#getParticipantType <em>Participant Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Uno#getVariantes <em>Variantes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.Uno#getRegles <em>Regles</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getUno()
 * @model
 * @generated
 */
public interface Uno extends EObject
{
  /**
   * Returns the value of the '<em><b>Nb Joueur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb Joueur</em>' containment reference.
   * @see #setNbJoueur(NbJoueur)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getUno_NbJoueur()
   * @model containment="true"
   * @generated
   */
  NbJoueur getNbJoueur();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Uno#getNbJoueur <em>Nb Joueur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb Joueur</em>' containment reference.
   * @see #getNbJoueur()
   * @generated
   */
  void setNbJoueur(NbJoueur value);

  /**
   * Returns the value of the '<em><b>Participant Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participant Type</em>' containment reference.
   * @see #setParticipantType(ParticipantType)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getUno_ParticipantType()
   * @model containment="true"
   * @generated
   */
  ParticipantType getParticipantType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Uno#getParticipantType <em>Participant Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participant Type</em>' containment reference.
   * @see #getParticipantType()
   * @generated
   */
  void setParticipantType(ParticipantType value);

  /**
   * Returns the value of the '<em><b>Variantes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variantes</em>' containment reference.
   * @see #setVariantes(Variantes)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getUno_Variantes()
   * @model containment="true"
   * @generated
   */
  Variantes getVariantes();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Uno#getVariantes <em>Variantes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variantes</em>' containment reference.
   * @see #getVariantes()
   * @generated
   */
  void setVariantes(Variantes value);

  /**
   * Returns the value of the '<em><b>Regles</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regles</em>' containment reference.
   * @see #setRegles(Regles)
   * @see org.xtext.example.mydsl.rulesUNO.RulesUNOPackage#getUno_Regles()
   * @model containment="true"
   * @generated
   */
  Regles getRegles();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rulesUNO.Uno#getRegles <em>Regles</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Regles</em>' containment reference.
   * @see #getRegles()
   * @generated
   */
  void setRegles(Regles value);

} // Uno
