/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.rulesUNO.Affectation;
import org.xtext.example.mydsl.rulesUNO.Attribut;
import org.xtext.example.mydsl.rulesUNO.ExpressionNumerique;
import org.xtext.example.mydsl.rulesUNO.RulesUNOPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Affectation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.impl.AffectationImpl#getAttribut <em>Attribut</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rulesUNO.impl.AffectationImpl#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AffectationImpl extends DeclarationImpl implements Affectation
{
  /**
   * The cached value of the '{@link #getAttribut() <em>Attribut</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribut()
   * @generated
   * @ordered
   */
  protected Attribut attribut;

  /**
   * The cached value of the '{@link #getExpression() <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression()
   * @generated
   * @ordered
   */
  protected ExpressionNumerique expression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AffectationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RulesUNOPackage.Literals.AFFECTATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribut getAttribut()
  {
    return attribut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttribut(Attribut newAttribut, NotificationChain msgs)
  {
    Attribut oldAttribut = attribut;
    attribut = newAttribut;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RulesUNOPackage.AFFECTATION__ATTRIBUT, oldAttribut, newAttribut);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttribut(Attribut newAttribut)
  {
    if (newAttribut != attribut)
    {
      NotificationChain msgs = null;
      if (attribut != null)
        msgs = ((InternalEObject)attribut).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RulesUNOPackage.AFFECTATION__ATTRIBUT, null, msgs);
      if (newAttribut != null)
        msgs = ((InternalEObject)newAttribut).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RulesUNOPackage.AFFECTATION__ATTRIBUT, null, msgs);
      msgs = basicSetAttribut(newAttribut, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RulesUNOPackage.AFFECTATION__ATTRIBUT, newAttribut, newAttribut));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressionNumerique getExpression()
  {
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression(ExpressionNumerique newExpression, NotificationChain msgs)
  {
    ExpressionNumerique oldExpression = expression;
    expression = newExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RulesUNOPackage.AFFECTATION__EXPRESSION, oldExpression, newExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExpression(ExpressionNumerique newExpression)
  {
    if (newExpression != expression)
    {
      NotificationChain msgs = null;
      if (expression != null)
        msgs = ((InternalEObject)expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RulesUNOPackage.AFFECTATION__EXPRESSION, null, msgs);
      if (newExpression != null)
        msgs = ((InternalEObject)newExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RulesUNOPackage.AFFECTATION__EXPRESSION, null, msgs);
      msgs = basicSetExpression(newExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RulesUNOPackage.AFFECTATION__EXPRESSION, newExpression, newExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RulesUNOPackage.AFFECTATION__ATTRIBUT:
        return basicSetAttribut(null, msgs);
      case RulesUNOPackage.AFFECTATION__EXPRESSION:
        return basicSetExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RulesUNOPackage.AFFECTATION__ATTRIBUT:
        return getAttribut();
      case RulesUNOPackage.AFFECTATION__EXPRESSION:
        return getExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RulesUNOPackage.AFFECTATION__ATTRIBUT:
        setAttribut((Attribut)newValue);
        return;
      case RulesUNOPackage.AFFECTATION__EXPRESSION:
        setExpression((ExpressionNumerique)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RulesUNOPackage.AFFECTATION__ATTRIBUT:
        setAttribut((Attribut)null);
        return;
      case RulesUNOPackage.AFFECTATION__EXPRESSION:
        setExpression((ExpressionNumerique)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RulesUNOPackage.AFFECTATION__ATTRIBUT:
        return attribut != null;
      case RulesUNOPackage.AFFECTATION__EXPRESSION:
        return expression != null;
    }
    return super.eIsSet(featureID);
  }

} //AffectationImpl
