/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.rulesUNO.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.rulesUNO.InstructionsBloc;
import org.xtext.example.mydsl.rulesUNO.RulesUNOPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Instructions Bloc</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InstructionsBlocImpl extends InstructionImpl implements InstructionsBloc
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InstructionsBlocImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RulesUNOPackage.Literals.INSTRUCTIONS_BLOC;
  }

} //InstructionsBlocImpl
