/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import istic.m2.idm.tp.uno.ui.internal.UnoActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RulesUNOExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(UnoActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		UnoActivator activator = UnoActivator.getInstance();
		return activator != null ? activator.getInjector(UnoActivator.ORG_XTEXT_EXAMPLE_MYDSL_RULESUNO) : null;
	}

}
